name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: debian-latest

    steps:
    - uses: docker/build-push-action@v5
    - name: Build the Docker image
